### ISSUE TITLE
Advanced CLI program to schedule scientific workflows across Europe

### ISSUE THREAD

**Issue by bgruening** [bgruening/project-ideas#17]
Advanced CLI program to schedule scientific workflows across Europe
---

**Supervisor:** Björn Grüning
**For degree:** Bachelor/Project
**Status:** Open/In progress/Completed (assigned to ...)
**Keywords:** workflows, Galaxy, python, REST-API

# Global context

Galaxy is one of the biggest bioinformatics open-source projects around and it provides access to HPC and Cloud resources for hundreds of thousands of researchers. Galaxy is usually used via a GUI to schedule workflows. In this thesis, a light-weight but powerful CLI should be developed to easily schedule workflows and get the workflow status.

# Project context

In this project, a tool should be developed that interfaces with the RESTful API of Galaxy and schedules jobs and workflows. Smart autocompletion should be integrated to automatically guide the user to missing parameters. Moreover, a fancy status report should be printed to the console, realtime updates would be great as well.

# Objectives of the project

Create a CLI to Galaxy to submit workflows and jobs of arbitrary size and report back to the user the status.

# Proposed agenda for the project

1. get familiar with the RESTful API of Galaxy
2. submit a workflow and tools via Python to Galaxy
3. get familiar with the python module `click` or similar libraries, especially the autocompletion feature
4. implement a `workflow run` feature
5. implement access to reports of the started workflow(s)

# Prerequisites

- Unix and Python experience
- access RESTful APIs
- good communication skills

# Further reading and useful links

- Learn the basics of [Galaxy 101](https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-101/tutorial.html).
- Learn about [tool development](https://planemo.readthedocs.io/en/latest/writing_standalone.html) in Galaxy.
- [Python click](https://click.palletsprojects.com/en/7.x/)
- https://en.wikipedia.org/wiki/Scientific_workflow_system

**Comment by simonbray** [comment]
Done (by me, not a student, whoops :))
