### ISSUE TITLE
GGplot2 in Galaxy

### ISSUE THREAD

**Issue by mtekman** [bgruening/project-ideas#19]
Implement a fully customisable GGPlot2 tool in Galaxy.

Galaxy XML is fully functional as seen here:
- https://github.com/galaxyproject/tools-iuc/pull/2484

The backend needs work.

This could be a good student project for someone who wants to get familiar with R and ggplot.

**Comment by bgruening** [comment]
Sure! But also please note that there are now a few ggplot2 based tools in IUC. I think people decided to make one tool per plot ... violine etc ...

**Comment by mtekman** [comment]
Ah I see. I guess it would also be impossible to cater for every possible ggplot use case, so it makes sense that people roll their own tools for specific plots.

Shall I close this, then?

**Comment by bgruening** [comment]
If you are missing plots, this is probably a good idea. If you don't need it, please feel free to close it.
