### ISSUE TITLE
Integration of BioJS into Galaxy

### ISSUE THREAD

**Issue by joachimwolff** [bgruening/project-ideas#5]
Integration of BioJS into Galaxy
---

**Supervisor:** Clemens Blank, Joachim Wolff
**For degree:** Project
**Status:** In progress: assigned to Dimitar Jovanov and Aveg Chaudhary
**Keywords:** Visualization, BioJS, Galaxy

# Project context
Galaxy is an open, web-based platform for data intensive research. The University of Freiburg is running a Galaxy server to serve all different needs of our researchers. Visualization is a key aspect in the understanding of data analysis for medical and biological research. The Javascript library BioJS provides powerful visualization of multiple biological data. The overall aim is to integrate specific BioJS modules into Galaxy via its plugin architecture.

**Comment by joachimwolff** [comment]
Project is finished.

**Comment by bgruening** [comment]
Do you really think it is finished? ;)

**Comment by joachimwolff** [comment]
At least this master project is. I don't know how we should handle finished projects (and their corresponding issues) from students which have still 'some' content left.

**Comment by bgruening** [comment]
I would handle this as `is the project idea` implemented or is still work left for others ...
